services:
  server:
    build:
      context: .
      target: release
    ports:
      - 8030:8030
    # volumes:
    #   - "/home/opc/beeMonitorContent/labs:/beeMonitorData/labs:rw"
    #   - "/home/opc/beeMonitorContent/tipizate:/beeMonitorData/tipizate:rw"
    #   - "/home/opc/beeMonitorContent/blog:/beeMonitorData/blog:rw"
    #   - "./.env:/app/.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beeMonitor.rule=Host(`beemonitor.blitzcloud.me`)"
      - "traefik.http.routers.beeMonitor.entrypoints=https"
      - "traefik.http.routers.beeMonitor.tls=true"
      - "traefik.http.services.beeMonitor.loadbalancer.server.port=8030"
      #Define midleware
      - "traefik.http.routers.beeMonitor.middlewares=my-traefikBouncer@file,my-cloudflarewarp@file"
    networks:
      - proxy
    restart: always
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # ports:
    #   - 27016:27017
    networks:
      - proxy
  mongo-express:
    image: mongo-express
    restart: always
    # ports:
    #   - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27016/
      ME_CONFIG_BASICAUTH: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dbInterface.rule=Host(`dbint.blitzcloud.me`)"
      - "traefik.http.routers.dbInterface.entrypoints=https"
      - "traefik.http.routers.dbInterface.tls=true"
      - "traefik.http.services.dbInterface.loadbalancer.server.port=8081"
      #Define midleware
      - "traefik.http.routers.dbInterface.middlewares=my-traefikBouncer@file,my-cloudflarewarp@file"
    networks:
      - proxy


networks:
  proxy:
    external: true
